default:
  headless: true
  max_workers: 3
  build_timeout: 1800
skip_services:
- pp-qrcode-cloud
- pp-claim-cloud
- pp-dynamic-order-cloud
- pp-exchange-console
- pp-e-signature-web
- pp-exchange-console
- pp-factory-service
- pp-file-service
- pp-gi-service
- pp-gi-web
- pp-ip-service
- pp-ip-template-service
- pp-ip-template-web
- pp-lt-external-service-api
- pp-node-aa-pdf-generator
- pp-parameter-service
- pp-parameter-web
services:
  sequential:
    # pp-lt-aims-web: DEVELOPMENT
    # pp-lt-aims-service-api: SP-22259
    # pp-lt-program-web: SP-23094
    # pp-node-aca: SP-22854_cancel_reason
  concurrent:
    # it-dependency: SP-21974-Epic
    pp-lt-aims-web: DEVELOPMENT
    pp-lt-aims-service-api: DEVELOPMENT
    # pp-public-api: SP-21974-Epic
    # pp-node-aca: SP-22854_cancel_reason
    # pp-final-report-service: release-5.3.37
    # pp-lt-program-web: SP-23094
    # pp-lt-doc-services-api: release-5.3.37
